### ISSUE TITLE
[version_0.5]Keyboard does not pop up automatically in search page 

### ISSUE THREAD

**Issue by Joeyd321** [Telenav-Search/search-android-demo-app#12]
Step:
1.Tap on search bar in search box , enter the search page 
2.Check system behavior 

Expect:
Keyboard will pop up automatically

Actual 
Keyboard does not pop up automatically ,  it will shows after click search box

**Comment by arambaghdasintellias** [comment]
Couldn't reproduce, on which screen does this issue happen ?

**Comment by Joeyd321** [comment]
> Couldn't reproduce, on which screen does this issue happen ?

In version 0.5, when you enter the search page , the key board not display automatically , after click text box , key board will show.

**Comment by arambaghdasintellias** [comment]
Fixed.

**Comment by Joeyd321** [comment]
Verify in version 0.6, result is PASS.
