### ISSUE TITLE
[version_0.5]Setting page issue

### ISSUE THREAD

**Issue by Joeyd321** [Telenav-Search/search-android-demo-app#14]
1.There are some repeat text display
2.The select environment item different from design 
<img width="289" alt="10" src="https://user-images.githubusercontent.com/101797921/158785787-f0b99a6b-7c96-4b95-8913-c3eabfc69ea7.png">
<img width="161" alt="design_10" src="https://user-images.githubusercontent.com/101797921/158786168-46e290db-5049-4d1e-9067-5a67345b346a.png">

**Comment by arambaghdasintellias** [comment]
Dublicate https://github.com/Telenav-Search/search-android-demo-app/issues/43
