### ISSUE TITLE
 [version_0.5]Food sub category display too more 

### ISSUE THREAD

**Issue by Joeyd321** [Telenav-Search/search-android-demo-app#15]
Food sub category display too more .
By design, there's only one line .
<img width="291" alt="5" src="https://user-images.githubusercontent.com/101797921/158787159-4a30948e-99e8-4f12-a57f-6dfa497ac2a1.png">
<img width="262" alt="design_5" src="https://user-images.githubusercontent.com/101797921/158787348-bf0eaaab-d69a-4efe-9c90-0da24f8cc689.png">

**Comment by arambaghdasintellias** [comment]
Dublicate https://github.com/Telenav-Search/search-android-demo-app/issues/33
