### ISSUE TITLE
[version_0.5]Should back to collapsed box not extend 

### ISSUE THREAD

**Issue by Joeyd321** [Telenav-Search/search-android-demo-app#18]
Step:
1. Launch app 
2. Tap on user button on the search box 
3. Tap back button on user page 
expect：
back to collapsed box
actual:
back to extend box
<img width="356" alt="design" src="https://user-images.githubusercontent.com/101797921/158932610-9661bb10-1206-4f9b-9eb7-e2eff9f10dae.png">

**Comment by arambaghdasintellias** [comment]
It should always collapse or it depends on previous state ?

**Comment by Joeyd321** [comment]
> 

It should depends on previous state.

**Comment by Joeyd321** [comment]
> > 
> 
> It should depends on previous state.
Sorry to close , reopen it.

**Comment by arambaghdasintellias** [comment]
Fixed.

**Comment by Joeyd321** [comment]
Verify in version 0.6, result is PASS.
