### ISSUE TITLE
 [version_0.5]Tap on map, poi detail info page does not collapse

### ISSUE THREAD

**Issue by Joeyd321** [Telenav-Search/search-android-demo-app#19]
step:
1.Enter a poi detail info page 
2.Tap on map 
expect:
Poi detail info page will collapse
actual:
poi detail info page does not collapse
<img width="678" alt="design_1" src="https://user-images.githubusercontent.com/101797921/158945605-a4b8e047-de89-404f-ab51-d4243d2c7bfa.png">

**Comment by arambaghdasintellias** [comment]
Fixed.

**Comment by Joeyd321** [comment]
Verify in version 0.6, result is PASS.
