### ISSUE TITLE
[version_0.5]It take long time to back, not good experience for user

### ISSUE THREAD

**Issue by Joeyd321** [Telenav-Search/search-android-demo-app#21]
1. It take long time that from poi detail info page back to category search page 
2. It take long time that from filters page back to category search page
![screen](https://user-images.githubusercontent.com/101797921/158946954-9b80ac56-21d9-4e52-8efb-961ab05863b0.jpg)

**Comment by arambaghdasintellias** [comment]
Couldn't speed up, it depends on sdk functions response time.
