### ISSUE TITLE
 [version_0.5]Parking and coffee poi icon not central display 

### ISSUE THREAD

**Issue by Joeyd321** [Telenav-Search/search-android-demo-app#22]
step:
1.Enter coffee poi detail page and check the poi icon in map 
2.Enter parking poi detail page and check the poi icon in map 
expect:
Parking and coffee poi icon central display 
actual:
Parking and coffee poi icon not central display 
<img width="293" alt="2" src="https://user-images.githubusercontent.com/101797921/158947404-3ef001a6-2fd4-47e4-b8ef-0891a8f12a34.png">
<img width="290" alt="2_2" src="https://user-images.githubusercontent.com/101797921/158947408-dff1750e-3835-4f9e-80a2-dea550b0ed17.png">

**Comment by arambaghdasintellias** [comment]
Fixed.
