### ISSUE TITLE
The predicted words don't display correctly

### ISSUE THREAD

**Issue by YesIamJeremyChen** [Telenav-Search/search-android-demo-app#24]
<img width="891" alt="Screen Shot 2022-03-21 at 6 05 17 PM" src="https://user-images.githubusercontent.com/70997856/159240188-2aa261f4-6cf7-4d0d-9327-a2103bcf9ef5.png">

**Comment by arambaghdasintellias** [comment]
Duplicate https://github.com/Telenav-Search/search-android-demo-app/issues/17
