### ISSUE TITLE
Issues in the parking filter page 

### ISSUE THREAD

**Issue by YesIamJeremyChen** [Telenav-Search/search-android-demo-app#26]
<img width="778" alt="Screen Shot 2022-03-21 at 6 08 24 PM" src="https://user-images.githubusercontent.com/70997856/159240662-b94a91c0-dc67-46b1-b1d1-3d429dbf2603.png">

**Comment by arambaghdasintellias** [comment]
Fixed.

**Comment by Joeyd321** [comment]
Verify in version 0.6, result is PASS.
