### ISSUE TITLE
Issues for the size of the views in main page

### ISSUE THREAD

**Issue by YesIamJeremyChen** [Telenav-Search/search-android-demo-app#28]
<img width="1104" alt="Screen Shot 2022-03-21 at 6 18 02 PM" src="https://user-images.githubusercontent.com/70997856/159242036-6a29c8d6-3e99-4447-80d5-24a6f7cc33c1.png">

**Comment by arambaghdasintellias** [comment]
2 will be fixed in https://github.com/Telenav-Search/search-android-demo-app/issues/33
3,5 will be fixed in https://github.com/Telenav-Search/search-android-demo-app/issues/41
