### ISSUE TITLE
Display issues for the page displaying recent history without keyboard

### ISSUE THREAD

**Issue by YesIamJeremyChen** [Telenav-Search/search-android-demo-app#29]
<img width="1142" alt="Screen Shot 2022-03-21 at 6 19 47 PM" src="https://user-images.githubusercontent.com/70997856/159242294-05aa6403-2fc4-4932-b8c8-9c7343dac74c.png">

**Comment by arambaghdasintellias** [comment]
Fixed 2-5 , 1 - it happens by system.
