### ISSUE TITLE
Issues for the page displaying recent history with predicted words 

### ISSUE THREAD

**Issue by YesIamJeremyChen** [Telenav-Search/search-android-demo-app#31]
<img width="1144" alt="Screen Shot 2022-03-21 at 6 20 53 PM" src="https://user-images.githubusercontent.com/70997856/159242656-326ad94a-d975-4310-b0c6-11025ef9c6ce.png">

**Comment by arambaghdasintellias** [comment]
Fixed. 
4. The same item is used here(https://github.com/Telenav-Search/search-android-demo-app/issues/41), will be fixed on scope of this task.
