### ISSUE TITLE
Issues for the page with search keywords

### ISSUE THREAD

**Issue by YesIamJeremyChen** [Telenav-Search/search-android-demo-app#34]
<img width="1090" alt="Screen Shot 2022-03-21 at 6 24 07 PM" src="https://user-images.githubusercontent.com/70997856/159242955-5a587adb-c441-4a61-a2c9-a5c8df7e5a12.png">

**Comment by arambaghdasintellias** [comment]
Fixed.

3. Duplicate  https://github.com/Telenav-Search/search-android-demo-app/issues/22
4. Duplicate https://github.com/Telenav-Search/search-android-demo-app/issues/33
