### ISSUE TITLE
Issues for the page to displaying POI detail while the bottom bar is in minimum size

### ISSUE THREAD

**Issue by YesIamJeremyChen** [Telenav-Search/search-android-demo-app#39]
<img width="1099" alt="Screen Shot 2022-03-21 at 6 27 46 PM" src="https://user-images.githubusercontent.com/70997856/159243561-58f62810-4412-41be-993b-fc92ec5bd377.png">

**Comment by arambaghdasintellias** [comment]
Fixed.
