### ISSUE TITLE
Issues for the page to display detail for EV Charge POI

### ISSUE THREAD

**Issue by YesIamJeremyChen** [Telenav-Search/search-android-demo-app#40]
<img width="1091" alt="Screen Shot 2022-03-21 at 6 29 12 PM" src="https://user-images.githubusercontent.com/70997856/159243739-5ea58925-ea51-4865-920d-c330251e1c9d.png">

**Comment by arambaghdasintellias** [comment]
Similar screen, will be fixed in https://github.com/Telenav-Search/search-android-demo-app/issues/38.
