### ISSUE TITLE
Issues for the delete button for deleting from favorite list 

### ISSUE THREAD

**Issue by YesIamJeremyChen** [Telenav-Search/search-android-demo-app#42]
<img width="1104" alt="Screen Shot 2022-03-21 at 6 30 55 PM" src="https://user-images.githubusercontent.com/70997856/159244038-95e1a98d-2b26-4aa4-ab1b-c6d5a573c66d.png">

**Comment by arambaghdasintellias** [comment]
Dublicate https://github.com/Telenav-Search/search-android-demo-app/issues/20
