### ISSUE TITLE
Issues for the settings page

### ISSUE THREAD

**Issue by YesIamJeremyChen** [Telenav-Search/search-android-demo-app#43]
<img width="1114" alt="Screen Shot 2022-03-21 at 6 31 56 PM" src="https://user-images.githubusercontent.com/70997856/159244103-d90d1578-37e1-49a2-9b2f-06a4fd9c22a0.png">

**Comment by jj123640131** [comment]
Duplicate to https://github.com/Telenav-Search/search-android-demo-app/issues/14
